### ISSUE TITLE
received header with unexpected rsv bits set: false:true:true

### ISSUE THREAD

**Issue by oslook** [nhooyr/websocket#391]
During my use of the library(server and client both v1.8.7), the server occasionally receives the following prompt, 

```
failed to get reader: received header with unexpected rsv bits set: false:true:true
```

which seems to be related to this part of the code.  

**write.go** L300:

```
	c.writeHeader.rsv1 = false
	if flate && (opcode == opText || opcode == opBinary) {
		c.writeHeader.rsv1 = true
	}
```

Could you please confirm if it is necessary to add the following code here?

```
	c.writeHeader.rsv1 = false
	c.writeHeader.rsv2 = false
	c.writeHeader.rsv3 = false
```

**Comment by vendion** [comment]
I'm getting something slightly similar using the same version: `failed to get reader: received header with unexpected rsv bits set: true:true:true`

**Comment by soypat** [comment]
Me too

**Comment by nhooyr** [comment]
That's quite concerning that all three of you guys are seeing that... I'd suggest disabling compression though it'll be disabled by default in the next release.

I'll go through the code again to see if I can find the bug. The autobahn compression tests pass fine under the race detector so I'm surprised to see a bug like this.

**Comment by nhooyr** [comment]
@soypat If possible, can you share the frames you checked with wireshark? Maybe I can replay them with the library and thus reproduce. That would help immensely in debugging.

**Comment by nhooyr** [comment]
There's been enough changes for v1.8.8 that whatever this was is likely fixed. Compression in particular is disabled by default now and I recommend keeping it that way. Let me know if you see it again once v1.8.8 is released.

**Comment by nhooyr** [comment]
Nvm I was able to reproduce, see https://github.com/nhooyr/websocket/commit/249edb209389a1b6fd3b1f79de78417982077284

**Comment by nhooyr** [comment]
Were you guys using the library through a proxy?

**Comment by nhooyr** [comment]
Nvm, that bug was from my proxy not working correctly. Fixed now.

**Comment by nhooyr** [comment]
Actually nvm, this is probably caused by #355 so I'll close after fixing that.

**Comment by nhooyr** [comment]
Done so closing.

**Comment by maggie44** [comment]
I still see this error on occasions. Seen it today on the latest release: `failed to get reader: received header with unexpected rsv bits set: true:true:false"`

Whenever I see it, it so far has always been the result of me having two readers open at the same time. It states `Only one Reader may be open at a time.`, but sometimes an error in my code generates this.

Not sure if the error message could be clearer for diagnosis. Adding this quick comment here in case anyone comes across this issue and finds this thread.

**Comment by nhooyr** [comment]
Ah yea that would do it. I'll add a link to this thread in that error message.

Could also add some protection here perhaps without much performance cost.

**Comment by maggie44** [comment]
I wonder if there is also a way to have two readers, where both (or multiple) receive the same message. This would be helpful for me in a number of scenarios.

**Comment by nhooyr** [comment]
There shouldn't be any scenario where you want to do a concurrent read on the connection. There should only ever be one goroutine reading from the connection. Can you clarify why you feel you need multiple readers or even why you're passing the reader around like that? Perhaps an example in code?

**Comment by maggie44** [comment]
On the multiple reader, makes sense. Closing and reopening or passing around, I read in a loop but some messages call a series of functions and those functions need to take over the connection and receive all future messages after their call. For those functions I need to either stop the loop and move the reader down or relay all messages through a channel on through another connection. 

Hard to fully explain, maybe at some point it will hit me how best to do it. Didn’t want to hijack the thread though, will think on it.

**Comment by GoldenSheep402** [comment]
The problem still appear in my project?

**Comment by jazzcake-diverse** [comment]
Hello, I also have similar problem in my project. in my log, "**readPacket() s.conn.ReadMessage() err: failed to get reader: received header with unexpected rsv bits set: true:false:true**"

It could be helpful if I leave code snippet?
-------
		default:
			ctx := context.Background()

			msgType, r, err := s.Conn.Reader(ctx)
			if err != nil {
				log.Warnf("session[ %d ] readPacket() s.conn.ReadMessage() msgType: %d, err: %s", s.sid, msgType, err.Error())
				s.packetChan <- Packet{S: s, Message: serializer.MakeDisconnected()}
				return
			}

			b, err := io.ReadAll(r)
			if err != nil {
				log.Warnf("session[ %d] io.ReadAll() err: %s", s.sid, err.Error())
				s.packetChan <- Packet{S: s, Message: serializer.MakeDisconnected()}
				return
			}

			// send packet to chan
			s.packetChan <- Packet{S: s, Message: b}

**Comment by mafredri** [comment]
@jazzcake-diverse I don't see anything wrong in your snippet, but there could be issues in the surrounding code. Have you made sure it's not possible `s.Conn.Reader` is being called simultaneously from different goroutines or places in the code?

**Comment by jazzcake-diverse** [comment]
@mafredri Thank you for feedback. The code snippet is part of goroutine, readPacket() which is run for each session(websocket.Conn from Accept). So I don't think it can be called simultaneously from other goroutine. In client side, I use 3 websocket, 1) UnrealEngine 5 websocket plugin, 2) Godot 4 Websocket, 3) this library as client. This error usually appear in Unreal and Godot side.

**Comment by SolomonSklash** [comment]
I am running into this issue as well:

`failed to get reader: received header with unexpected rsv bits set: true:true:false`
as well as
`failed to get reader: received header with unexpected rsv bits set: false:false:true`

I only have a single Reader, and it only seems to happen when I do testing of large (100MB+) file sizes. The first error, I received 20463354 bytes, and the second 17177066.
